'use client'
import Head from 'next/head'
import { Typography, useTheme } from '@mui/material'
import { useSettings } from 'src/hooks/useSettings'

export default function Home() {
  const theme = useTheme()
  console.log("theme: ", theme)

  // UseSetting là các hook tạo ra từ context
  const { settings } = useSettings();
  console.log('theme', {theme, settings});

  return (
    <>
      <Head>
        <title>Lập trình thật dễ</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Typography>Hello world updated</Typography>
    </>
  )
}
