'use client'
import Head from 'next/head'
import { Box, Typography, useTheme } from '@mui/material'
import { useSettings } from 'src/hooks/useSettings'
import CustomTextField from 'src/components/text-field'

export default function Home() {
  const theme = useTheme()
  console.log('theme 1: ', theme)

  // UseSetting là các hook tạo ra từ context
  const { settings } = useSettings()
  console.log('theme 2', { theme, settings })

  return (
    <>
      <Head>
        <title>Lập trình thật dễ</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {/* Box trong material UI cũng giống như thẻ <div> */}
      <Box sx={{ margin: 6, width: '200px' }}>
        <CustomTextField id='outlined-multiline-flexible' label='Multiline' />
      </Box>
    </>
  )
}
